services:
  llm-key-rotator:
    build:
      context: ..
      dockerfile: .prodcontainer/Dockerfile
    container_name: llm-key-rotator
    restart: unless-stopped
    ports:
      - "8990:8990"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gemini-api.rule=Host(`gemini.marvwal.uk`)"
      - "traefik.http.routers.gemini-api.entrypoints=web"
      - "traefik.http.routers.gemini-api.middlewares=gemini-api-prefix"
      - "traefik.http.middlewares.gemini-api-prefix.addprefix.prefix=/geminigoogle"
      -  "traefik.http.services.gemini-api.loadbalancer.server.port=8990"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
    name: traefik
